{% set name = "pytransit" %}
{% set version = "2.6.16" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytransit-{{ version }}.tar.gz
  sha256: aca60be3de9c9723efef1f6f1a30c3eabb7a0a20341e7fe1094650de2e21411a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - arviz
    - numpy
    - scipy
    - pandas
    - xarray
    - pytables
    - uncertainties
    - numba
    - astropy
    - matplotlib-base
    - tqdm
    - semantic_version
    - setuptools
    - deprecated
    - seaborn
    - emcee
    - pyopencl
    - corner
    - celerite
    - meepmeep

test:
  imports:
    - pytransit
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Fast and painless exoplanet transit light curve modelling.
  license: GPL-2.0-only
  license_file: LICENSE
  home: https://github.com/hpparvi/PyTransit

extra:
  recipe-maintainers:
    - hpparvi
